### ISSUE TITLE
配置完成后启动出现错误

### ISSUE THREAD

**Issue by aknyzsd** [Cypas/nonebot_plugin_disconnect_notice#10]
报错ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
![image](https://github.com/Cypas/nonebot_plugin_disconnect_notice/assets/121467598/0b8cdc62-d389-4413-9e70-170e728b54e1)
![image](https://github.com/Cypas/nonebot_plugin_disconnect_notice/assets/121467598/22834d3f-7424-4dfa-b9b9-e234b4c4c497)

**Comment by Cypas** [comment]
![image](https://github.com/Cypas/nonebot_plugin_disconnect_notice/assets/53274578/d8b6e75d-39f3-4825-8b59-27bb4004c18b)
这不是我插件的报错啊，是nonememe的，请找这个插件的作者进行反馈

**Comment by aknyzsd** [comment]
打扰了，感谢
