### ISSUE TITLE
能不能修改一下在主动退出的时候不发送邮件呢（或者在短时间内批量bot掉线时合并邮件）

### ISSUE THREAD

**Issue by aknyzsd** [Cypas/nonebot_plugin_disconnect_notice#11]
举个例子，在用gocq手动停止某个bot的时候也会收到邮件，这个还好。
我在退出整个bot进程的时候，有时会出现批量发送邮件的情况，这个能不能修改一下，一下十几封邮件到我信箱里多少有点受不住

**Comment by Cypas** [comment]
这个我有反馈低调佬(nonebot2仓库拥有者)，他说ws无法判断是哪边断开的连接，主动停止nb时也会先断开ws，之后再运行插件及框架的结束代码，这个问题无法解决。
短时间内多次掉线不推送的实现方案倒是可以考虑下

**Comment by aknyzsd** [comment]
或者考虑一下单位时间内多次掉线合并发送，感谢佬

**Comment by Cypas** [comment]
现在有重连宽限时间的配置项，主动退出已经不再批量发送邮件
