### ISSUE TITLE
新的推送方式建议——server酱 或者 pushplus推送加

### ISSUE THREAD

**Issue by qllokirin** [Cypas/nonebot_plugin_disconnect_notice#13]
[pushplus微信推送](https://www.pushplus.plus/)和[server酱](https://sct.ftqq.com/)都支持微信推送，扫码获得token后填入，只需要一个request的可以推送消息了，很方便，前者不限次数，后者一天免费五次。佬有意向新增一下这个功能吗，感觉获取邮箱授权码相比之下会有点繁琐

**Comment by Cypas** [comment]
好的我抽空看看他们文档

**Comment by Cypas** [comment]
已添加pushplus公众号推送方式
插件新增配置项
disconnect_notice_mode_list
disconnect_notice_pushplus_token
具体用法见readme教程及配置项

**Comment by qllokirin** [comment]
> 已添加pushplus公众号推送方式 插件新增配置项 disconnect_notice_mode_list disconnect_notice_pushplus_token 具体用法见readme教程及配置项

**非常感谢能够抽时间回复并修改，实测可以成功推送**

不过还有意向优化一些小细节吗
1. 比如我向下面这样填写，其他字段不写的情况下，启动后会发消息提示`缺少mail配置项......`，感觉改成有pushplus时检查`disconnect_notice_pushplus_token`字段，有mail时检测mail相关的字段会好一点

```
disconnect_notice_mode_list=["pushplus"]
disconnect_notice_pushplus_token="xxxxxxxx"
```

2. README里面的指令`掉线测试`改成`/掉线测试`感觉会好一点
3. 有没有意向增加一下名字参数呢，一起推送过来，这样比QQ号有识别度一点

```
info = await bot.call_api("get_stranger_info",user_id=bot_id)
nickname = info['nickname']
```
这样写应该能获取到昵称

**Comment by Cypas** [comment]
1,2已修改，3的话不是每种适配器都实现了get_stranger_info方法，一些适配器可能压根取不到bot个人信息，要通用一点的方案要么是自己填写bot_id与name的映射字典

**Comment by qllokirin** [comment]
> 1,2已修改，3的话不是每种适配器都实现了get_stranger_info方法，一些适配器可能压根取不到bot个人信息，要通用一点的方案要么是自己填写bot_id与name的映射字典

好的 非常感谢您的回复

**Comment by Cypas** [comment]
server酱也已经接入

**Comment by qllokirin** [comment]
https://github.com/Cypas/nonebot_plugin_disconnect_notice/issues/15#issuecomment-2548498181
