### ISSUE TITLE
推荐加入bot_offline事件判断

### ISSUE THREAD

**Issue by qllokirin** [Cypas/nonebot_plugin_disconnect_notice#15]
nc和lgr目前已经支持bot_offline事件，下面是我用的代码（使用nc或lrg时掉线时ws是不会断开的）

```
offline = on_notice(priority=1, block=False)
@offline.handle()
async def _(event: Event):
    if event.get_event_name() == "notice.bot_offline":
        des = json.loads(event.get_event_description().replace("'", '"'))
        logger.error("机器人掉线啦")
        logger.error(des['self_id'], des['message'], des['tag'])
```

**Comment by Cypas** [comment]
nc是哪一个协议？lgr是onebot可以加入

**Comment by qllokirin** [comment]
https://github.com/NapNeko/NapCatQQ
两个的这个事件是一样的好像

**Comment by Cypas** [comment]
> nc和lgr目前已经支持bot_offline事件，下面是我用的代码（使用nc或lrg时掉线时ws是不会断线的）
> 
> ```
> offline = on_notice(priority=1, block=False)
> @offline.handle()
> async def _(event: Event):
>     if event.get_event_name() == "notice.bot_offline":
>         des = json.loads(event.get_event_description().replace("'", '"'))
>         logger.error("机器人掉线啦")
>         logger.error(des['self_id'], des['message'], des['tag'])
> ```

这个event事件里完整的json文本能发我一份吗

**Comment by qllokirin** [comment]
我测试了lgr是这样的
```
12-12 16:23:57 [SUCCESS] nonebot | OneBot V11 3363527264 | [notice.bot_offline]: {'time': 1733991837, 'self_id': 3363527264, 'post_type': 'notice', 'notice_type': 'bot_offline', 'tag': '你的帐号当前登录已失效，请重新登录
。', 'message': '下线通知'}
```

```
print(event.get_event_description())
print(type(event.get_event_description()))
# {'time': 1733991837, 'self_id': 3363527264, 'post_type': 'notice', 'notice_type': 'bot_offline', 'tag': '你的帐号当前登录已失效，请重新登录。', 'message': '下线通知'}
# <class 'str'>
```

**Comment by Cypas** [comment]
nc和lgr没有单独标识符用来区别的话，只能统一输出平台名了

**Comment by qllokirin** [comment]
> nc和lgr没有单独标识符用来区别的话，只能统一输出平台名了

是nc还是lgr感觉问题不大，只要有qq号就能起到提醒作用就够了（我觉得）

**Comment by Cypas** [comment]
你下载一下源码然后替换到服务器看看吧，我没有lgr环境，不好测试，没问题的话我就发版了

**Comment by qllokirin** [comment]
![image](https://github.com/user-attachments/assets/34e64866-9872-4e77-acd1-4ce88acb4a58)
lgr测试↑

![image](https://github.com/user-attachments/assets/1244d956-1c67-4ad1-ad9e-c1f63390bf47)
nc测试↑

没问题 都可以正常通报

之前没看到邮件，抱歉啦

**Comment by qllokirin** [comment]
顺带一提我之前推荐的pushplus已经变味儿了
```
2024年8月1日起未实名的用户将会无法调用发送消息接口和支付功能。请尽快 完成实名认证！ 具体说明：实名认证说明

注意:手机号注册人需与填写的姓名和身份证保持一致

实名认证每次均需支付1元认证费，用于第三方校验接口
```
盒盒 又收钱又收集资料，如果大佬有心力的话还是把pushplus删了吧

**Comment by Cypas** [comment]
新版本已发布，pushplus的推送还是保留了，config缺省配置和readme都改成了推荐server酱

**Comment by qllokirin** [comment]
> 新版本已发布，pushplus的推送还是保留了，config缺省配置和readme都改成了推荐server酱

辛苦了，谢谢大佬的维护
